// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const activateUserByEmail = `-- name: ActivateUserByEmail :exec
UPDATE users SET active = TRUE WHERE email = $1
`

func (q *Queries) ActivateUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, activateUserByEmail, email)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email) VALUES ($1, $2) RETURNING id
`

type CreateUserParams struct {
	Username string
	Email    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deactivateUserByEmail = `-- name: DeactivateUserByEmail :exec
UPDATE users SET active = FALSE WHERE email = $1
`

func (q *Queries) DeactivateUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deactivateUserByEmail, email)
	return err
}

const deleteUserByUsername = `-- name: DeleteUserByUsername :exec
DELETE FROM users WHERE username = $1
`

func (q *Queries) DeleteUserByUsername(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, deleteUserByUsername, username)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, active, username, email, created_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Active,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, active, username, email, created_at
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Active,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
